#!/usr/bin/sh

SRC=`pwd`
SRC_CONFIG=$SRC/.config
SRC_CONFIG_ST2=$SRC_CONFIG/sublime-text-2/Packages
SRC_CONFIG_ST3=$SRC_CONFIG/sublime-text-3/Packages

DEST=$HOME
DEST_CONFIG=$DEST/.config
DEST_CONFIG_ST2=$DEST_CONFIG/sublime-text-2/Packages
DEST_CONFIG_ST3=$DEST_CONFIG/sublime-text-3/Packages

cd $DEST && echo "$DEST"
ln -s --backup=t $SRC/.profile && echo " + .profile"
ln -s --backup=t $SRC/.vim && echo " + .vim"
ln -s --backup=t $SRC/.vimrc && echo " + .vimrc"
ln -s --backup=t $SRC/.Xdefaults && echo " + .Xdefaults"
ln -s --backup=t $SRC/.wallpaper && echo " + .wallpaper"

mkdir -p $DEST_CONFIG
cd $DEST_CONFIG && echo "$DEST_CONFIG"
ln -s --backup=t $SRC_CONFIG/awesome && echo " + awesome"
ln -s --backup=t $SRC_CONFIG/fontconfig && echo " + fontconfig"

mkdir -p $DEST_CONFIG_ST2
cd $DEST_CONFIG_ST2 && echo "$DEST_CONFIG_ST2"
ln -s --backup=t $SRC_CONFIG_ST2/User && echo " + User"

mkdir -p $DEST_CONFIG_ST3
cd $DEST_CONFIG_ST3 && echo "$DEST_CONFIG_ST3"
ln -s --backup=t $SRC_CONFIG_ST3/User && echo " + User"
